import { Check, Clipboard, Download, QrCode as QrCodeIcon, ScanLine, Share2 } from "lucide-react";
import { useRef, useState } from "react";
import QRCode from "react-qr-code";
import type { QrSettings } from "../../types/qrCode";
import "./QrPreview.css";

interface Props { value:string; settings:QrSettings; }
export function QrPreview({value,settings}:Props){
 const previewRef=useRef<HTMLDivElement>(null); const [copied,setCopied]=useState(false); const normalized=value.trim(); const hasValue=Boolean(normalized); const bytes=hasValue?new TextEncoder().encode(normalized).length:0;
 async function copy(){if(!hasValue)return;await navigator.clipboard.writeText(normalized);setCopied(true);setTimeout(()=>setCopied(false),1800)}
 function svgSource(){const source=previewRef.current?.querySelector("svg");if(!source)return null;const margin=settings.margin;const unit=100/(21+margin*2);const offset=margin*unit;const inner=100-offset*2;const clone=source.cloneNode(true) as SVGElement;clone.setAttribute("x",String(offset));clone.setAttribute("y",String(offset));clone.setAttribute("width",String(inner));clone.setAttribute("height",String(inner));const logo=settings.logo?`<rect x="38" y="38" width="24" height="24" rx="4" fill="${settings.background}"/><image href="${settings.logo}" x="40" y="40" width="20" height="20" preserveAspectRatio="xMidYMid meet"/>`:"";return `<svg xmlns="http://www.w3.org/2000/svg" width="${settings.size}" height="${settings.size}" viewBox="0 0 100 100"><rect width="100" height="100" fill="${settings.background}"/>${new XMLSerializer().serializeToString(clone)}${logo}</svg>`}
 function save(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function downloadSvg(){const source=svgSource();if(source)save(new Blob([source],{type:"image/svg+xml;charset=utf-8"}),"gen-qrcode.svg")}
 async function rasterBlob(type:"image/png"|"image/jpeg"){const source=svgSource();if(!source)throw new Error("QR Code indisponível");const url=URL.createObjectURL(new Blob([source],{type:"image/svg+xml"}));const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=reject;image.src=url});const canvas=document.createElement("canvas");canvas.width=settings.size;canvas.height=settings.size;const context=canvas.getContext("2d");if(!context)throw new Error("Canvas indisponível");context.fillStyle=settings.background;context.fillRect(0,0,settings.size,settings.size);context.drawImage(image,0,0,settings.size,settings.size);URL.revokeObjectURL(url);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Falha na exportação")),type,.95))}
 async function downloadRaster(type:"image/png"|"image/jpeg"){try{save(await rasterBlob(type),`gen-qrcode.${type==="image/png"?"png":"jpg"}`)}catch(error){console.error(error);alert("Não foi possível exportar a imagem.")}}
 async function share(){try{const file=new File([await rasterBlob("image/png")],"gen-qrcode.png",{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"Meu QR Code",files:[file]})}else{await navigator.clipboard.writeText(normalized);alert("Compartilhamento nativo indisponível. O conteúdo foi copiado.")}}catch(error){if((error as Error).name!=="AbortError")console.error(error)}}
 return <section className="qr-preview" aria-live="polite"><div className="qr-preview-header"><div className="qr-preview-heading"><span className="qr-preview-icon"><ScanLine size={18}/></span><div><span className="qr-preview-tag">Visualização</span><h2>Seu QR Code</h2></div></div><p>Personalize, teste com a câmera e exporte no formato ideal.</p></div><div className={`qr-preview-content ${hasValue?"is-generated":""}`}>{hasValue?<><div ref={previewRef} className="qr-preview-code" style={{background:settings.background,padding:`${Math.min(settings.margin*3+8,38)}px`}}><QRCode value={normalized} size={256} level={settings.level} bgColor={settings.background} fgColor={settings.foreground} title="QR Code gerado"/>{settings.logo&&<span className="qr-logo" style={{background:settings.background}}><img src={settings.logo} alt=""/></span>}</div><div className="qr-preview-details"><div className="qr-preview-status"><span className="qr-preview-status-icon"><Check size={14}/></span><div><strong>QR Code pronto</strong><span>{bytes} bytes · correção {settings.level}</span></div></div><div className="qr-preview-actions"><button className="qr-preview-action" onClick={copy}>{copied?<Check size={16}/>:<Clipboard size={16}/>} {copied?"Copiado":"Copiar"}</button><button className="qr-preview-action" onClick={share}><Share2 size={16}/> Compartilhar</button></div></div><div className="export-grid"><button onClick={()=>downloadRaster("image/png")}><Download size={15}/> PNG</button><button onClick={()=>downloadRaster("image/jpeg")}><Download size={15}/> JPEG</button><button onClick={downloadSvg}><Download size={15}/> SVG</button></div><div className="qr-preview-payload"><span>Conteúdo codificado</span><p>{normalized}</p></div></>:<div className="qr-preview-empty"><div className="qr-preview-empty-icon"><QrCodeIcon size={38}/></div><strong>Nenhum QR Code gerado</strong><p>Preencha o formulário para visualizar o resultado.</p></div>}</div></section>
}
